plugin.xml
Target manifests are listed for phone, windows and windows80 separately. Consolidate them and use a single package.appxmanifest target.
=> CB-8687 consolidate manifest targets

src/ios/CDVCapture.m
Apparently this is a trivial change but I'd like someone to look it over.
This is where I got the fix:
https://github.com/inkling/Subliminal/issues/169
=> CB-9249 Fix iOS warnings in Media Capture plugin Part 2

src/windows/CaptureProxy.js
wrapped the file.moveAsync() function with a check for file and return CaptureError.CAPTURE_NO_MEDIA_FILES when file is undefiened
=> CB-10690 windows: fix crash when user cancels/closes photo app

src/android/Capture.java
Android
Fixes an image capture not to throw a FileUriExposedException on Android 7.0
https://issues.apache.org/jira/browse/CB-11995
Tested on Android 7.0 emulator as well as on various API level 19-22 emulators.
=> CB-11995 (android) Do not pass a file uri to the camera

src/android/Capture.java
Android
Catch ActivityNotFoundException when there is no app that can handle audio capture
Closes #102 
Tested on Android 8 device without capture app
=> GH-102 Catch ActivityNotFoundException

.eslintrc.yml, package.json, src/browser/CaptureProxy.js, src/windows/CaptureProxy.js, src/windows/MediaFile.js, tests/tests.js, www/CaptureAudioOptions.js, www/CaptureError.js, www/CaptureImageOptions.js, www/CaptureVideoOptions.js, www/ConfigurationData.js, www/MediaFile.js, www/MediaFileData.js, www/android/init.js, www/capture.js, www/helpers.js
Consistency across our codebases. Part of https://github.com/apache/cordova/issues/142
=> refactor(eslint): use cordova-eslint /w fix

src/ios/CDVCapture.m
Breaking because removes old ios 6-7-8-9 code.
Replaces UIAlertView deprecated on iOS 8 with UIAlertController
add missing self
removes ios < 6 code
replaces deprecated openURL with the newer one with more params
removes deprecated `setStatusBarStyle` methods
removes deprecated `- (NSUInteger)supportedInterfaceOrientations` methods
=> breaking(ios): remove code warnings

plugin.xml
Android
Permission `android.permission.RECORD_VIDEO` does [not exist](https://developer.android.com/reference/android/Manifest.permission.html).
Fix #199
Also described as a _made-up permission_ in this [SO post](https://stackoverflow.com/questions/37755734/unknown-permission-android-permission-record-video).
Android guides on [audio](https://developer.android.com/guide/topics/media/mediarecorder) and [video](https://developer.android.com/guide/topics/media/camera) recording with MediaRecorder only refer to **RECORD_AUDIO** and some other permissions but never to this one.
build
=> Android: Remove unknown permission android.permission.RECORD_VIDEO

tests/plugin.xml
n/a
Remove the `cordova-plugin-media` dependency from the test.
The plugin is not a dependency of the release package, so it may not be necessary for the test.
deleted `cordova-plugin-media` dependency
n/a - check gh actions
=> test: remove cordova-plugin-media dependency

plugin.xml, src/android/Capture.java
Android
Allow building applications using Android SDK 33, support for Android 13
Remove deprecated READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions and replace with new READ_MEDIA_IMAGES, READ_MEDIA_VIDEO and READ_MEDIA_AUDIO
Capture video and audio
=> feat(android)!: support API 33+ permissions

src/ios/CDVCapture.m
iOS
Fixes #267
i.e. Recording audio doesn't work on iOS 6.2 or newer.
I changed setting category `AVAudioSessionCategoryPlayAndRecord` before creating `AVAudioRecorder`. 
This is according to the comment https://github.com/apache/cordova-plugin-media-capture/issues/267#issuecomment-1472150858 .
In my local environment, I tested by creating cordova sample project and confirm the recording method (`navigator.device.capture.captureAudio`) works well on following devices.
iPhone SE 2th  iOS 16.4.1 (a)
iPhone 12  iOS 15.0
iPad Air 4th   iOS 16.3.1
=> fix(ios): set category before creating AVAudioRecorder

package.json
Package
Warn logged while adding plugin with verbose option:
```
$ cordova plugin add cordova-plugin-media-capture -d
...
Ignoring invalid version in cordova-plugin-media-capture cordovaDependencies: >=1.4.4 (must be a single version <= latest or an upper bound)
...
```
Using single version `1.4.4` is [interpreted](https://cordova.apache.org/docs/en/10.x/guide/hybrid/plugins/index.html#specifying-cordova-dependencies) as _>=1.4.4_ so indeed actual value can be simplified.
=> fix: use single version in cordovaDependencies

README.md, src/ios/CDVCapture.m, www/CaptureVideoOptions.js
iOS
Use `quality` param for video capture on iOS too.
Previously no configuration was done about it, meaning that the quality used  for capture was _medium_ as iOS default value.
Here is my suggested implementation based on previous PR #162 by @larrybahr with changes after my review and more tests + aligned default to `1` for iOS as it is for Android.
Follow iOS logic about video quality: [doc](https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619154-videoquality?language=objc)
`quality` value of `0` for [UIImagePickerControllerQualityTypeLow](https://developer.apple.com/documentation/uikit/uiimagepickercontrollerqualitytype/uiimagepickercontrollerqualitytypelow?language=objc), `0.5` for [UIImagePickerControllerQualityTypeMedium](https://developer.apple.com/documenta …
=> feat(ios): support capture 'quality' param for videos

www/helpers.js
www
Returned MediaFiles objects for captured media are missing `lastModified` (_null_) and `end` (_0_).
The [helpers.wrapMediaFiles](https://github.com/ath0mas/cordova-plugin-media-capture/blob/master/www/helpers.js#L28) method is using the MediaFile empty constructor, and attributes are set afterward.
But given [MediaFile constructor](https://github.com/ath0mas/cordova-plugin-media-capture/blob/master/www/MediaFile.js#L36) is simply calling its parent [cordova-plugin-file.File constructor](https://github.com/apache/cordova-plugin-file/blob/master/www/File.js#L31), we can understand that some File attributes will never be redefined properly.
Directly calling the constructor with all the params values resolves this problem in a clean manner.
Returned MediaFiles objects now have correct …
=> fix(MediaFiles): return missing 'lastModified' and 'end' attributes

src/android/Capture.java
Android
Prevent app crash after capture and show error if no content or no access to it
1. minimal fix #227 
Unify null checks for all three capture types, first on retrieved intent data uri (failing with `CAPTURE_NO_MEDIA_FILES`), and then on no mediaFile created (failing with `CAPTURE_INTERNAL_ERR`)
1. Simplify how video uri is retrieved from Video capture intent (see #210 comment)
App crashing because of audio capture in some conditions (see #227 comment) now resolves with failure instead.
Not perfect, expecting #215 work on FileProvider to solve the problem but for now it is not an app crash anymore.
=> fix(android): prevent app crash caused by NPE on intent data or mediaFile

src/ios/CDVCapture.m
iOS
Capturing audio is returning a mediaDictionary without its `type` attribute.
1. `getMediaDictionaryFromPath` should always set `type` for returned fileDict, either using "type" param or determined from file
1. audio type should not be forced to "audio/wav"
If "type" param is forced, returned fileDict uses it too.
And then, do capture audio on iOS to have an object with filled mimeType determined from file, usually "audio/x-wav".
=> fix(ios): set type attribute for captured audio

src/ios/CDVCapture.m
closes #186
This PR is a copy of #186 but rebased against the current the main branch to resolve conflicts. 
See #186 for more details.
I have already tested and approved the changes from #186.
=> fix(ios): CAPTURE_APPLICATION_BUSY error when dismissing modal by swipe

src/ios/CDVCapture.m
closes #185
This PR is a copy of #185 but rebased against the current the main branch to resolve conflicts. 
See #185 for more details.
I have tested and confirmed that the UI looks correctly with #185.
fixes #176
fixes #208
=> fix(ios): UI sizing of the audio capture controller according to parent view size

plugin.xml, src/android/Capture.java
Android
As discussed on #288, broad media permissions (`READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO`, `READ_MEDIA_AUDIO`) policy will be enforced on August 31, 2024, threatening the Google Play approval of apps using this plugin.
> For a more privacy preserving experience for users, we’re introducing the [Photo and Video Permissions policy](https://support.google.com/googleplay/android-developer/answer/13986130) to reduce the number of apps permitted to request broad photo/video permissions ([READ_MEDIA_IMAGES](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES) and [READ_MEDIA_VIDEO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VIDEO)). Apps may only access photos and videos for purposes directly related to app functionality. …
=> fix(android): remove broad media permissions

plugin.xml, src/android/Capture.java, src/android/FileProvider.java, src/android/res/xml/mediacapture_provider_paths.xml
Android
In an app that I develop, the captured file needs to be moved to a specific app directory. In current plugin version, it works for most Android overlays versions, but for some, it does not (#289, #286, #233, #277, #221, #196 and #210) due to Android's limitation to use external files.
The PR [!215 ](https://github.com/apache/cordova-plugin-media-capture/pull/215) did exactly the job I needed, so I just retrieved @chriskhongqarma's changes and applied them to current master branch with suggestions.
The idea is to use a ContentProvider (a [FileProvider](https://developer.android.com/reference/androidx/core/content/FileProvider), in this case) as a common database to store files, so that both our app and other apps can get access to.
An empty file (audio, image, video) with unique …
=> Fix(android): save media capture to File Provider

plugin.xml
Android
Permissions `RECORD_AUDIO` is not requested at runtime and unnecessary.
Replace #211 to fix #209?
See previous PR #211 and issue #209.
But contrary to both of them, stating that `The external permissions are already handled by the cordova-plugin-file, which this plugin depends on.`, seems wrong now: `cordova-plugin-file` ^8.0.0 does not declare any permission at all inside its `plugin.xml`, so this plugin can still do it.
=> Android: remove RECORD_AUDIO permission

src/android/Capture.java
Android
Using the Media Store query API requires broad range external storage permissions on API 28 and earlier (including API 29 if legacy storage rules are used). This will be important for a future PR to remove unnecessary permissions.
Additionally, the logic of checking the number of images in the media store is flawed as external sources (outside of the application) can add or remove content at any time. There is no guarantee that checking the quantity of images will result in the intended behaviour of removing duplicate images. There is also no guarantee that the image selected is even the image that is a "duplicate".
The Camera plugin had the same logic which was [removed](https://github.com/apache/cordova-plugin-camera/pull/907) for the same reasons.
Lastly, recent changes have …
=> fix(android): remove usage of Media Store queries
